version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: aima
      POSTGRES_PASSWORD: aima2023
      POSTGRES_DB: aimaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
